---

# Deploy and Configure Flask Applicaiton

- hosts: all
  become: true
  become_method: sudo
  vars:
    app_home: /webapps/devops
    app_repo: https://bitbucket.org/azneita/devops-challenge.git
  roles:
    - { role: provisioning }